### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wirus15** [wirus15/bombajs#8]
system:
- [ ] add lint for typescript
- [x] remove angular completely

gameplay:
- [x] fly in animation
- [x] shield fading
- [x] ship movement based on acceleration (test)
- [x] gui - simple
- [x] gaining points for destroying enemies
- [x] fix world bounds flicker
- [x] fix destroyed player's ship's movement
- [x] add lives counter
- [x] add game over sign and game restarting
- [x] add other enemies based on player level
- [x] add bosses
- [x] add boss fire
- [x] add enemy fire
- [x] add other weapon types
- [x] add weapon pickups
- [x] add upgrade pickups - double damage, armor and repair
- [x] add upgrade timeouts
- [x] add obstacles (rocks)
- [ ] side-to-side animation
- [ ] gui - with icons and custom font
- [x] fix boss flickering
- [x] add engine boost
- [x] add ship hit animation
- [x] add bullet destroy animation
- [ ] add more bullet types
- [ ] add more fire sounds
- [ ] fix weapon types depending on enemy level (type + damage)

New features:
- [ ] weapon upgrades
- [ ] rockets following targets
- [ ] background details - planets, galaxies, nebulas...
- [ ] stationary enemies - rocker launchers, etc.
- [ ] new graphics
- [ ] enemy fly routes, sequences, groups, etc.
- [ ] change the way shield works - damage reduction
